name:                metal
version:             0.1.0.0
github:              "Joald/metal"
license:             BSD3
author:              "Jacek Olczyk"
maintainer:          "jacek.olczyk98@gmail.com"
copyright:           "2021 Jacek Olczyk"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Joald/metal#readme>

dependencies:
- base >= 4.7 && < 5
- filepath >= 1.4.2.1
- optparse-applicative >= 0.16.1.0

library:
  source-dirs: src

executables:
  metal-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - metal

tests:
  metal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - metal
